version: "3.8"

services:
  # === Jitsi Web (frontend) ===
  web:
    image: jitsi/web:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
      - "127.0.0.1:${HTTPS_PORT}:443"
    links:
      - prosody:xmpp.meet.jitsi
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      - ${CONFIG}/web/load-test:/usr/share/jitsi-meet/load-test:Z
    env_file: .env
    depends_on:
      - prosody
      - jvb

  # === Prosody (XMPP) ===
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    expose:
      - "${XMPP_PORT:-5222}"
      - "${PROSODY_S2S_PORT:-5269}"
      - "5347"
      - "${PROSODY_HTTP_PORT:-5280}"
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    env_file: .env

  # === Jicofo ===
  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    ports:
      - "0.0.0.0:${JICOFO_REST_PORT:-8888}:8888"
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    env_file: .env
    depends_on:
      - prosody

  # === JVB (VideoBridge) ===
  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    ports:
      - "${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp"
      - "0.0.0.0:${JVB_COLIBRI_PORT:-8080}:8080"
    volumes:
      - ${CONFIG}/jvb:/config:Z
    env_file: .env
    depends_on:
      - prosody

  # === Jitsi Keycloak Adapter (Nordeck) ===
  jka:
    image: ghcr.io/nordeck/jitsi-keycloak-adapter:v20250314
    restart: unless-stopped
    environment:
      # где слушает адаптер
      PORT: 9001

      # Keycloak (внешний)
      KEYCLOAK_ORIGIN: https://sso.labexp.xyz
      KEYCLOAK_REALM: LabExp
      KEYCLOAK_CLIENT_ID: k8s-meet
      KEYCLOAK_MODE: query

      # публичный адрес Jitsi
      JITSI_ORIGIN: ${PUBLIC_URL}

      # базовый путь — ВАЖНО: /oidc (совместимо с их шаблоном body.html)
      BASE_PATH: /oidc
      ALLOW_GUESTS: "false"
      SECURE_COOKIE: "true"
      LOG_LEVEL: info

      # JWT для Jitsi (HS256 по общему секрету)
      JWT_ALG: HS256
      JWT_HASH: SHA-256
      JWT_APP_ID: ${JWT_APP_ID}
      JWT_APP_SECRET: ${JWT_APP_SECRET}
      JWT_EXP_SECOND: 3600
    ports:
      - "127.0.0.1:9001:9001"
    env_file: .env
