version: "3.8"

services:
  # === Jitsi Web (frontend) ===
  web:
    image: jitsi/web:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
      - "127.0.0.1:${HTTPS_PORT}:443"
    links:
      - prosody:xmpp.meet.jitsi
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      - ${CONFIG}/web/load-test:/usr/share/jitsi-meet/load-test:Z
    # Критичные флаги — прямо в environment (чтобы Coolify точно прокинул)
    environment:
      ENABLE_AUTH: "1"
      AUTH_TYPE: "jwt"
      ENABLE_GUESTS: "1"
      ENABLE_AUTO_OWNER: "0"
      PUBLIC_URL: ${PUBLIC_URL}
      ENABLE_XMPP_WEBSOCKET: "1"
      ENABLE_COLIBRI_WEBSOCKET: "1"
      XMPP_SERVER: prosody
      XMPP_DOMAIN: meet.jitsi
      XMPP_AUTH_DOMAIN: auth.meet.jitsi
      XMPP_GUEST_DOMAIN: guest.meet.jitsi
      XMPP_MUC_DOMAIN: muc.meet.jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
    env_file: .env
    depends_on: [prosody, jvb]

  # === Prosody (XMPP) ===
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    expose:
      - "${XMPP_PORT:-5222}"
      - "${PROSODY_S2S_PORT:-5269}"
      - "5347"
      - "${PROSODY_HTTP_PORT:-5280}"
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    environment:
      ENABLE_AUTH: "1"
      AUTH_TYPE: "jwt"
      ENABLE_GUESTS: "1"
      JWT_SIGN_TYPE: "hs256"
      JWT_APP_ID: ${JWT_APP_ID}
      JWT_APP_SECRET: ${JWT_APP_SECRET}
      JWT_ACCEPTED_ISSUERS: ${JWT_APP_ID}
      JWT_ACCEPTED_AUDIENCES: ${JWT_APP_ID}
    env_file: .env

  # === Jicofo ===
  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    ports:
      - "0.0.0.0:${JICOFO_REST_PORT:-8888}:8888"
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    environment:
      ENABLE_AUTH: "1"
      AUTH_TYPE: "jwt"
      ENABLE_AUTO_OWNER: "0"
    env_file: .env
    depends_on: [prosody]

  # === JVB (VideoBridge) ===
  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-unstable}
    restart: unless-stopped
    ports:
      - "${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp"
      - "0.0.0.0:${JVB_COLIBRI_PORT:-8080}:8080"
    volumes:
      - ${CONFIG}/jvb:/config:Z
    env_file: .env
    depends_on: [prosody]

  # === Jitsi Keycloak Adapter (Nordeck) ===
  jka:
    image: ghcr.io/nordeck/jitsi-keycloak-adapter:v20250314
    restart: unless-stopped
    environment:
      PORT: 9001
      KEYCLOAK_ORIGIN: https://sso.labexp.xyz
      KEYCLOAK_REALM: LabExp
      KEYCLOAK_CLIENT_ID: k8s-meet
      KEYCLOAK_MODE: query
      JITSI_ORIGIN: ${PUBLIC_URL}

      # Важно: под /oidc (совместимо с их body.html)
      BASE_PATH: /oidc
      ALLOW_GUESTS: "false"
      SECURE_COOKIE: "true"
      LOG_LEVEL: info

      # HS256 JWT (общий секрет с Prosody/Jitsi)
      JWT_ALG: HS256
      JWT_HASH: SHA-256
      JWT_APP_ID: ${JWT_APP_ID}
      JWT_APP_SECRET: ${JWT_APP_SECRET}
      JWT_EXP_SECOND: 3600
    ports:
      - "127.0.0.1:9001:9001"
    env_file: .env
